# Generated by Django 3.1.7 on 2021-04-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='tag',
        ),
    ]
