# Generated by Django 3.1.7 on 2021-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210404_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
