# Generated by Django 3.1.7 on 2021-04-04 16:49

import datetime
from django.db import migrations, models
import main.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 4), validators=[main.validators.validators.validate_age]),
        ),
    ]
