# Generated by Django 3.1.7 on 2021-04-04 19:43

import datetime
from django.db import migrations, models
import main.validators.validators
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210404_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 4), validators=[main.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
    ]
