# Generated by Django 3.1.7 on 2021-04-04 19:57

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210404_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/'),
        ),
    ]
