# Generated by Django 3.1.7 on 2021-04-10 21:43

import datetime
from django.db import migrations, models
import main.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210404_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 10), validators=[main.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
    ]
