# Generated by Django 3.1.7 on 2021-04-11 08:37

import datetime
from django.db import migrations, models
import main.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210411_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 11), validators=[main.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
    ]
