# Generated by Django 3.1.7 on 2021-04-12 11:44

import datetime
from django.db import migrations, models
import django.utils.timezone
import main.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата заполнения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 12), validators=[main.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
    ]
