# Generated by Django 3.1.7 on 2021-04-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210412_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='pub_date',
        ),
    ]
