# Generated by Django 3.1.7 on 2021-04-23 22:53

import datetime
from django.conf import settings
from django.db import migrations, models
import main.validators.validators
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0029_auto_20210412_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_confirmed',
            field=models.PositiveIntegerField(default=1234, verbose_name='Подтверждено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 4, 23), validators=[main.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
        migrations.CreateModel(
            name='SMSConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='Код подтверждения')),
                ('status', models.CharField(max_length=14, verbose_name='Статус ответа сервера')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
