# Generated by Django 3.1.7 on 2021-05-04 17:47

import datetime
from django.db import migrations, models
import main.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210424_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 5, 4), validators=[main.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
    ]
