# Generated by Django 3.1.7 on 2021-05-05 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210505_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликованно'),
        ),
    ]
